from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from enum import Enum
import polars as pl
from dataclasses import dataclass
from quant_repo.factory.vector_tester import VectorBacktester


class PipelineStage(Enum):
    DISCOVERY = 0
    VECTOR_FILTER = 1
    EVENT_SIM = 2
    VALIDATION = 3
    PASSED = 4
    REJECTED = 5


@dataclass
class StrategyCandidate:
    name: str
    params: Dict[str, Any]
    current_stage: PipelineStage = PipelineStage.DISCOVERY
    metrics: Dict[str, Any] = field(default_factory=dict)
    rejection_reason: Optional[str] = None


class PipelineOrchestrator:
    """
    Manages the Alpha Factory lifecycle for a strategy candidate.
    """

    def __init__(self):
        self.vector_tester = VectorBacktester()

    def run_pipeline(
        self, candidate: StrategyCandidate, data: pl.DataFrame
    ) -> StrategyCandidate:
        print(f"[Factory] Processing {candidate.name}...")

        # Stage 1: Vector Filter
        if candidate.current_stage == PipelineStage.DISCOVERY:
            candidate = self._run_vector_filter(candidate, data)

        if candidate.current_stage == PipelineStage.REJECTED:
            return candidate

        # Stage 2: Event Sim (Mocked for now as per plan, we connect real one later)
        # In a real impl, this would call BacktestRunner
        candidate = self._run_event_sim(candidate)

        return candidate

    def _run_vector_filter(
        self, candidate: StrategyCandidate, data: pl.DataFrame
    ) -> StrategyCandidate:
        print(f"  -> Running Stage 1 (Vector Filter)...")
        # Assume candidate params define the signal logic
        # For this prototype, we'll assume 'data' already has a 'signal' column populated
        # normally generated by a SignalGenerator using candidate.params

        # Run Vector Tester
        res = self.vector_tester.run(data, signal_col="signal")
        candidate.metrics["stage1_sharpe"] = res["sharpe"]

        print(f"     Sharpe: {res['sharpe']:.2f}")

        # Filter Logic
        if res["sharpe"] < 0.5:
            candidate.current_stage = PipelineStage.REJECTED
            candidate.rejection_reason = (
                f"Stage 1 Sharpe too low: {res['sharpe']:.2f} < 0.5"
            )
        else:
            candidate.current_stage = PipelineStage.VECTOR_FILTER  # Passed Vector

        return candidate

    def _run_event_sim(self, candidate: StrategyCandidate) -> StrategyCandidate:
        if candidate.current_stage == PipelineStage.REJECTED:
            return candidate

        print(f"  -> Running Stage 2 (Event Simulation)...")
        # Placeholder for full loop
        # Check Stage 1 Sharpe to decide Stage 2 Result for this prototype

        # If Stage 1 Sharpe > 1.0, we assume Stage 2 passes
        if candidate.metrics.get("stage1_sharpe", 0) > 1.0:
            candidate.current_stage = PipelineStage.EVENT_SIM
            candidate.metrics["stage2_sharpe"] = (
                candidate.metrics["stage1_sharpe"] * 0.8
            )  # Degradation
        else:
            candidate.current_stage = PipelineStage.REJECTED
            candidate.rejection_reason = "Stage 2 Failed (Mock)"

        return candidate
